// app-config.js.tpl
// This file is auto-generated by Terraform
window.APP_CONFIG = {
    region: "${aws_region}",
    userPoolId: "${user_pool_id}",
    clientId: "${client_id}",
    apiEndpoint: "${api_endpoint}"
};